language: node_js

dist: focal

group: focal

node_js:
  - 14
  - 16
  - 18
  - 20

before_install:
  - wget -qO - https://package.perforce.com/perforce.pubkey | sudo apt-key add -
  - npm i -g npm@8
  - npm --version

script:
  - npm run build
  - npm run test-travis || travis_terminate 1
  - npm run lint
  - npm run check-packages
