language: node_js

dist: focal

group: focal

jobs:
  include:
  - stage: "Unit tests"
    node_js: 18
    env: TEST_SUITE=unit-travis
  - node_js: 20
    env: TEST_SUITE=unit-travis
  - node_js: 22
    env: TEST_SUITE=unit-travis
  - stage: "Integration tests"
    node_js: 20
    env: TEST_SUITE=integration-travis
  - stage: "Regression tests"
    node_js: 20
    env: TEST_SUITE=regression
  - stage: "Examples tests"
    node_js: 20
    env: TEST_SUITE=examples
  - stage: "Security scans"
    name: "Secrets scanning"
    language: python
    python: 3.10
    before_install:
      - pip install --upgrade "git+https://github.com/ibm/detect-secrets.git@master#egg=detect-secrets"
      - detect-secrets --version
    script:
      - detect-secrets audit .secrets.baseline
    after_failure:
      - echo "For more details refer to https://w3.ibm.com/w3publisher/detect-secrets"
  - name: "Vulnerability scanning"
    node_js: 20
    before_install:
      - node --version
      - npm --version
    script: npm audit --audit-level moderate


before_install:
  - node --version
  - npm --version
  - ./scripts/cicd/prepare-integration-test-config.sh

script:
  - npm run build
  - npm run "test-${TEST_SUITE}" || travis_terminate 1
  - if [[ "${TEST_SUITE}" == "unit" ]] ; then
      npm run lint ;
    fi
  - npm run check-packages
